# Generated by Django 3.0.1 on 2019-12-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='desc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
